scraper:
  rootUrl: https://en.wikipedia.org/wiki/Open-source_intelligence
spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    rest:
      base-path: /data-rest-api
jpa:
  hibernate:
    ddl-auto: none
